typography_spectrum: 0.5977420608978719
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#606060'
    - '#c3c3c3'
    - '#d2122b'
  brandStrength: 0
  lightness: 0.8391698359046131
  saturation: 0.07679402502253652
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jeff Oster
  email: jeff@jeffoster.com
  url: 'http://jeffoster.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/59f9dcb9-0ac2-4b5a-8fd6-a8cfb5a72703.jpg
name: Jeff Oster Music
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Listen!
    url: 'http://jeffoster.com'
    type: external
  - name: Watch!
    url: 'http://www.youtube.com/ffejretso'
    type: external
favicon: null
title: Imagine...Miles meets Pink Floyd
description: jeffoster.com
purpose: []
